### ISSUE TITLE
Add list of required packages to readme

### ISSUE THREAD

**Issue by norcalbiostat** [EllaKaye/advent-of-code-website-template#1]
Consider adding that you need the `quarto` package as well installed (not just `aochelpers`). For someone (like me) who uses the quarto built into Rstudio i had never needed to use this package. And I didn't get the error until building the site.

**Comment by EllaKaye** [comment]
Thank you so much for spotting this and reporting it 🙏 

The use of the `quarto` package is extraneous. It was only used in an appendix on Session Info for the posts, left over from when I adapted the post-template from my personal site. 

I figured the best fix for this, rather than place an additional burden on the user to install the package, was just removed the appendix from the template. This makes the posts cleaner as well. So that's what I've done.
